# Generated by Django 5.0 on 2023-12-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='albums',
            field=models.ManyToManyField(to='musicians.album'),
        ),
    ]
